export { default as ErrorOne } from './ErrorOne.vue'
export { default as ErrorTwo } from './ErrorTwo.vue'
export { default as ErrorThree } from './ErrorThree.vue'
export { default as ErrorFour } from './ErrorFour.vue'
export { default as ErrorFive } from './ErrorFive.vue'
export { default as ErrorSix } from './ErrorSix.vue'
export { default as ErrorSeven } from './ErrorSeven.vue'
export { default as ErrorEight } from './ErrorEight.vue'
